from typing import TypeVar, Protocol

from pydantic import BaseModel

T = TypeVar("T")


class DAO[T](Protocol):
    async def create(self, model_data: BaseModel) -> T: ...
    async def update(self, object_id: int, model_data: BaseModel) -> bool: ...
    async def delete(self, object_id: int) -> bool: ...
    async def list(self, page_size: int, page_number: int) -> list[T]: ...
    async def find(self, object_id: int) -> T | None: ...
    async def count(self) -> int: ...
